# Generated by Django 5.1.3 on 2024-11-17 07:58

import sacco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=sacco.models.generate_unique_name),
        ),
    ]
